services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: sst-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
