spring:
  application:
    name: sst-services
  datasource:
    url: jdbc:postgresql://localhost:5432/your_db_name
    username: your_db_user
    password: your_db_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Options: create, update, validate, none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true # Logs SQL queries in the console
        format_sql: true # Formats SQL queries in the logs
        use_sql_comments: true # Adds comments to SQL queries for readability
